version: '3'
services:
  database:
    ports:
      - '5432:5432'
    image: postgres
    environment:
      - POSTGRES_DB=abcd-test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - 'database-data:/var/lib/postgresql/data'
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - '.:/code'
    depends_on:
      - database
volumes:
  database-data: null
