export const calendar = [
  {month: 'January', days: []},
  {month: 'February', days: []},
  {month: 'March', days: []},
  {month: 'April', days: []},
  {
    month: 'May',
    days: [
      {date: 1, day: 'Friday'},
      {date: 2, day: 'Saturday'},
      {date: 3, day: 'Sunday'},
      {date: 4, day: 'Monday'},
      {date: 5, day: 'Tuesday'},
      {date: 6, day: 'Wednesday'},
      {date: 7, day: 'Thursday'},
      {date: 8, day: 'Friday'},
      {date: 9, day: 'Saturday'},
      {date: 10, day: 'Sunday'},
      {date: 11, day: 'Monday'},
      {date: 12, day: 'Tuesday'},
      {date: 13, day: 'Wednesday'},
      {date: 14, day: 'Thursday'},
      {date: 15, day: 'Friday'},
      {date: 16, day: 'Saturday'},
      {date: 17, day: 'Sunday'},
      {date: 18, day: 'Monday'},
      {date: 19, day: 'Tuesday'},
      {date: 20, day: 'Wednesday'},
      {date: 21, day: 'Thursday'},
      {date: 22, day: 'Friday'},
      {date: 23, day: 'Saturday'},
      {date: 24, day: 'Sunday'},
      {date: 25, day: 'Monday'},
      {date: 26, day: 'Tuesday'},
      {date: 27, day: 'Wednesday'},
      {date: 28, day: 'Thursday'},
      {date: 29, day: 'Friday'},
      {date: 30, day: 'Saturday'},
      {date: 31, day: 'Sunday'},
    ],
  },
  {
    month: 'June',
    days: [
      {date: 1, day: 'Monday'},
      {date: 2, day: 'Tuesday'},
      {date: 3, day: 'Wednesday'},
      {date: 4, day: 'Thursday'},
      {date: 5, day: 'Friday'},
      {date: 6, day: 'Saturday'},
      {date: 7, day: 'Sunday'},
      {date: 8, day: 'Monday'},
      {date: 9, day: 'Tuesday'},
      {date: 10, day: 'Wednesday'},
      {date: 11, day: 'Thursday'},
      {date: 12, day: 'Friday'},
      {date: 13, day: 'Saturday'},
      {date: 14, day: 'Sunday'},
      {date: 15, day: 'Monday'},
      {date: 16, day: 'Tuesday'},
      {date: 17, day: 'Wednesday'},
      {date: 18, day: 'Thursday'},
      {date: 19, day: 'Friday'},
      {date: 20, day: 'Saturday'},
      {date: 21, day: 'Sunday'},
      {date: 22, day: 'Monday'},
      {date: 23, day: 'Tuesday'},
      {date: 24, day: 'Wednesday'},
      {date: 25, day: 'Thursday'},
      {date: 26, day: 'Friday'},
      {date: 27, day: 'Saturday'},
      {date: 28, day: 'Sunday'},
      {date: 29, day: 'Monday'},
      {date: 30, day: 'Tuesday'},
    ],
  },
  {month: 'July', days: []},
  {month: 'August', days: []},
  {month: 'September', days: []},
  {month: 'October', days: []},
  {month: 'November', days: []},
  {month: 'December', days: []},
]
